// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCbfiRZcwP2htqNhv2L8Bk4qCs_hq1Ye10',
//     appId: '1:62108937144:web:dce113a5a9adfaed45fd4d',
//     messagingSenderId: '62108937144',
//     projectId: 'servicemateapp-5a6a5',
//     authDomain: 'servicemateapp-5a6a5.firebaseapp.com',
//     storageBucket: 'servicemateapp-5a6a5.firebasestorage.app',
//     measurementId: 'G-D0ZR5MRL05',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDb5HMkegujYtNyKENXhaf1Knli6DSPyd4',
//     appId: '1:62108937144:android:9efa22e221ba0a3745fd4d',
//     messagingSenderId: '62108937144',
//     projectId: 'servicemateapp-5a6a5',
//     storageBucket: 'servicemateapp-5a6a5.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAeLdA23lNjFxQ48Y6eZpmuBSnt3RdKlrU',
//     appId: '1:62108937144:ios:b7cd4c4adf5e974945fd4d',
//     messagingSenderId: '62108937144',
//     projectId: 'servicemateapp-5a6a5',
//     storageBucket: 'servicemateapp-5a6a5.firebasestorage.app',
//     iosBundleId: 'com.example.servicemate',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAeLdA23lNjFxQ48Y6eZpmuBSnt3RdKlrU',
//     appId: '1:62108937144:ios:b7cd4c4adf5e974945fd4d',
//     messagingSenderId: '62108937144',
//     projectId: 'servicemateapp-5a6a5',
//     storageBucket: 'servicemateapp-5a6a5.firebasestorage.app',
//     iosBundleId: 'com.example.servicemate',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCbfiRZcwP2htqNhv2L8Bk4qCs_hq1Ye10',
//     appId: '1:62108937144:web:eceed1548919c57f45fd4d',
//     messagingSenderId: '62108937144',
//     projectId: 'servicemateapp-5a6a5',
//     authDomain: 'servicemateapp-5a6a5.firebaseapp.com',
//     storageBucket: 'servicemateapp-5a6a5.firebasestorage.app',
//     measurementId: 'G-TZ8Z2L151Y',
//   );
// }
